### ISSUE TITLE
dump graph failed

### ISSUE THREAD

**Issue by suesunss** [hugegraph/hugegraph-tools#30]
使用 dump 命令的时候，报错：

```java
Graph 'graph_name' start dump!
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" com.baidu.hugegraph.exception.ToolsException: Exception occurred while querying shards of vertices(after 3 retries)
	at com.baidu.hugegraph.base.RetryManager.retry(RetryManager.java:56)
	at com.baidu.hugegraph.manager.BackupManager.backupVertices(BackupManager.java:126)
	at com.baidu.hugegraph.manager.DumpGraphManager.dump(DumpGraphManager.java:67)
	at com.baidu.hugegraph.cmd.HugeGraphCommand.execute(HugeGraphCommand.java:158)
	at com.baidu.hugegraph.cmd.HugeGraphCommand.main(HugeGraphCommand.java:310)
Caused by: class java.lang.IllegalArgumentException: The split-size must be >= 1048576 bytes, but got 0
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44)
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:69)
	at com.baidu.hugegraph.rest.RestClient.get(RestClient.java:192)
	at com.baidu.hugegraph.api.traverser.VerticesAPI.shards(VerticesAPI.java:65)
	at com.baidu.hugegraph.driver.TraverserManager.vertexShards(TraverserManager.java:227)
	at com.baidu.hugegraph.manager.BackupManager.lambda$backupVertices$0(BackupManager.java:127)
	at com.baidu.hugegraph.base.RetryManager.retry(RetryManager.java:51)
	... 4 more
```
 
测试的图是 loader 的 `examples` 下提供了默认图。

**Comment by zhoney** [comment]
@suesunss 感谢反馈！

问题已修复，参见 #32
