### ISSUE TITLE
Exception in thread "main" class java.lang.IllegalStateException: Can't find task scheduler for graph 'hugegraph[hugegraph]' 

### ISSUE THREAD

**Issue by cyberpsyche** [hugegraph/hugegraph-tools#51]
在执行以下命令时都报与task scheduler相关的问题，但我从未设置过与task相关的任务，请问如何解决？ 谢谢！！！ @javeme 

**$ ./bin/hugegraph graph-clear -c "I'm sure to delete all data"**

Exception in thread "main" class java.lang.IllegalStateException: Can't find task scheduler for graph 'hugegraph[hugegraph]'
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44)
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:100)
	at com.baidu.hugegraph.rest.RestClient.delete(RestClient.java:232)
	at com.baidu.hugegraph.api.graphs.GraphsAPI.clear(GraphsAPI.java:82)
	at com.baidu.hugegraph.driver.GraphsManager.clear(GraphsManager.java:54)
	at com.baidu.hugegraph.manager.GraphsManager.clear(GraphsManager.java:44)
	at com.baidu.hugegraph.cmd.HugeGraphCommand.execute(HugeGraphCommand.java:222)
	at com.baidu.hugegraph.cmd.HugeGraphCommand.main(HugeGraphCommand.java:379)

**$ ./bin/hugegraph task-list**
Exception in thread "main" class java.lang.IllegalStateException: Can't find task scheduler for graph 'hugegraph[hugegraph]'
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44)
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:100)
	at com.baidu.hugegraph.rest.RestClient.get(RestClient.java:212)
	at com.baidu.hugegraph.api.task.TaskAPI.list(TaskAPI.java:66)
	at com.baidu.hugegraph.driver.TaskManager.list(TaskManager.java:54)
	at com.baidu.hugegraph.manager.TasksManager.list(TasksManager.java:52)
	at com.baidu.hugegraph.cmd.HugeGraphCommand.execute(HugeGraphCommand.java:261)
	at com.baidu.hugegraph.cmd.HugeGraphCommand.main(HugeGraphCommand.java:379)

**$ ./bin/hugegraph task-clear --force**
Exception in thread "main" class java.lang.IllegalStateException: Can't find task scheduler for graph 'hugegraph[hugegraph]'
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44)
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:100)
	at com.baidu.hugegraph.rest.RestClient.get(RestClient.java:212)
	at com.baidu.hugegraph.api.task.TaskAPI.list(TaskAPI.java:66)
	at com.baidu.hugegraph.driver.TaskManager.list(TaskManager.java:54)
	at com.baidu.hugegraph.manager.TasksManager.list(TasksManager.java:52)
	at com.baidu.hugegraph.manager.TasksManager.clear(TasksManager.java:72)
	at com.baidu.hugegraph.cmd.HugeGraphCommand.execute(HugeGraphCommand.java:288)
	at com.baidu.hugegraph.cmd.HugeGraphCommand.main(HugeGraphCommand.java:379)

**Comment by javeme** [comment]
@cyberpsyche 因为这些命令都是跟task相关的。可以说明一下是怎么触发的吗？服务端日志中是否有错误信息？
