### ISSUE TITLE
migrate 在restoring模式下报错

### ISSUE THREAD

**Issue by chencjiajy** [hugegraph/hugegraph-tools#81]
hugegraph-tools version: 1.5.0
hugegraph-server vertion: 0.10.4

执行命令： `./bin/hugegraph --url http://172.30.5.166:8183 --graph hugegraph migrate --target-url http://172.30.5.166:8183 --target-graph hugegraph1`
报错 “Exception in thread "main" class java.lang.IllegalArgumentException: Must provide schema id if in RESTORING mode”

日志如下：

Migrate graph 'hugegraph' from 'http://172.30.5.166:8183' to 'http://172.30.5.166:8183' as 'hugegraph1'
Property key backup started
Property key backup finished: 20
Vertex label backup started
Vertex label backup finished: 15
Edge label backup started
Edge label backup finished: 22
Index label backup started
Index label backup finished: 26
Vertices backup started
Vertices has been backup: 2261
Vertices backup finished: 2261
Edges backup started
Edges has been backup: 5390
Edges backup finished: 5390

backup summary: {
	property key number: 20,
	vertex label number: 15,
	edge label number: 22,
	index label number: 26,
	vertex number: 2261,
	edge number: 5390,
}
cost time(s): 0
Graph 'hugegraph1' start restore in mode 'RESTORING'!
Property key restore started
Property key restore finished: 20
Vertex label restore started
Vertex label restore finished: 15
Edge label restore started
Edge label restore finished: 22
Index label restore started
Exception in thread "main" class java.lang.IllegalArgumentException: Must provide schema id if in RESTORING mode
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:47)
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:93)
	at com.baidu.hugegraph.rest.AbstractRestClient.post(AbstractRestClient.java:198)
	at com.baidu.hugegraph.rest.AbstractRestClient.post(AbstractRestClient.java:172)
	at com.baidu.hugegraph.api.schema.IndexLabelAPI.create(IndexLabelAPI.java:49)
	at com.baidu.hugegraph.driver.SchemaManager.addIndexLabel(SchemaManager.java:187)
	at com.baidu.hugegraph.driver.SchemaManager.addIndexLabel(SchemaManager.java:182)
	at com.baidu.hugegraph.manager.RestoreManager.lambda$restoreIndexLabels$9(RestoreManager.java:237)
	at com.baidu.hugegraph.manager.BackupRestoreBaseManager.read(BackupRestoreBaseManager.java:186)
	at com.baidu.hugegraph.manager.RestoreManager.restore(RestoreManager.java:249)
	at com.baidu.hugegraph.manager.RestoreManager.restoreIndexLabels(RestoreManager.java:242)
	at com.baidu.hugegraph.manager.RestoreManager.restore(RestoreManager.java:83)
	at com.baidu.hugegraph.cmd.HugeGraphCommand.execute(HugeGraphCommand.java:233)
	at com.baidu.hugegraph.cmd.HugeGraphCommand.main(HugeGraphCommand.java:427)

**Comment by zhoney** [comment]
fixed in：https://github.com/hugegraph/hugegraph-client/pull/118
