### ISSUE TITLE
备份好的数据再恢复数据，其中index_label出现错误

### ISSUE THREAD

**Issue by chobits102** [hugegraph/hugegraph-tools#87]
版本号：
hugegraph-0.9.2
hugegraph-tools-1.5.0
1，现有图数据hugegraphdoctor，通过备份，--graph hugegraphdoctor backup -t 'property_key,vertex_label,edge_label,index_label,vertex,edge' --directory ./backupJson

2，新建了图数据 hugegraphdoctor_backup， 通过命令转模式--graph hugegraphdoctor_backup graph-mode-set -m RESTORING并清除数据，--graph hugegraphdoctor_backup graph-clear -c "I'm sure to delete all data"

3，恢复数据到hugegraphdoctor_backup，通过命令 --graph hugegraphdoctor_backup restore -t 'property_key,vertex_label,edge_label,index_label,vertex,edge' --directory ./backupJson

4,发生错误如下：
Graph 'hugegraphdoctor_backup' start restore in mode 'RESTORING'!
Property key restore started
Property key restore finished: 57
Vertex label restore started
Vertex label restore finished: 10
Edge label restore started
Edge label restore finished: 9
Index label restore started
Exception in thread "main" class java.lang.IllegalArgumentException: Must provide schema id if in RESTORING mode
at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:47)
at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:93)
at com.baidu.hugegraph.rest.AbstractRestClient.post(AbstractRestClient.java:198)
at com.baidu.hugegraph.rest.AbstractRestClient.post(AbstractRestClient.java:172)
at com.baidu.hugegraph.api.schema.IndexLabelAPI.create(IndexLabelAPI.java:49)
at com.baidu.hugegraph.driver.SchemaManager.addIndexLabel(SchemaManager.java:187)
at com.baidu.hugegraph.driver.SchemaManager.addIndexLabel(SchemaManager.java:182)
at com.baidu.hugegraph.manager.RestoreManager.lambda$restoreIndexLabels$9(RestoreManager.java:237)
at com.baidu.hugegraph.manager.BackupRestoreBaseManager.read(BackupRestoreBaseManager.java:186)
at com.baidu.hugegraph.manager.RestoreManager.restore(RestoreManager.java:249)
at com.baidu.hugegraph.manager.RestoreManager.restoreIndexLabels(RestoreManager.java:242)
at com.baidu.hugegraph.manager.RestoreManager.restore(RestoreManager.java:83)
at com.baidu.hugegraph.cmd.HugeGraphCommand.execute(HugeGraphCommand.java:191)
at com.baidu.hugegraph.cmd.HugeGraphCommand.main(HugeGraphCommand.java:427)

**Comment by imbajin** [comment]
duplicate, close this one
